/*
 * @Descripttion: element抽离
 * @version: 
 * @Author: TJ
 * @Date: 2021-04-20 08:51:48
 * @LastEditors: TJ
 * @LastEditTime: 2021-05-25 15:00:20
 */

// import 'element-plus/lib/theme-chalk/index.css';
import '../assets/css/element-variables.scss'
import 'element-plus/lib/theme-chalk/display.css';
import 'element-plus/packages/theme-chalk/src/base.scss'
import {
    // ElAlert,
    // ElAside,
    // ElAutocomplete,
    ElAvatar,
    // ElBacktop,
    ElBadge,
    // ElBreadcrumb,
    // ElBreadcrumbItem,
    ElButton,
    ElButtonGroup,
    // ElCalendar,
    ElCard,
    // ElCarousel,
    // ElCarouselItem,
    // ElCascader,
    // ElCascaderPanel,
    ElCheckbox,
    ElCheckboxButton,
    ElCheckboxGroup,
    ElCol,
    ElCollapse,
    ElCollapseItem,
    ElCollapseTransition,
    ElColorPicker,
    ElContainer,
    ElDatePicker,
    ElDialog,
    ElDivider,
    // ElDrawer,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    // ElFooter,
    ElForm,
    ElFormItem,
    // ElHeader,
    ElIcon,
    ElImage,
    ElInput,
    ElInputNumber,
    // ElLink,
    // ElMain,
    ElMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElOption,
    ElOptionGroup,
    // ElPageHeader,
    ElPagination,
    // ElPopconfirm,
    // ElPopover,
    // ElPopper,
    ElProgress,
    ElRadio,
    // ElRadioButton,
    ElRadioGroup,
    // ElRate,
    ElRow,
    ElScrollbar,
    ElSelect,
    // ElSlider,
    // ElStep,
    // ElSteps,
    ElSubmenu,
    ElSwitch,
    ElTabPane,
    ElTable,
    ElTableColumn,
    ElTabs,
    ElTag,
    // ElTimePicker,
    // ElTimeSelect,
    // ElTimeline,
    // ElTimelineItem,
    ElTooltip,
    // ElTransfer,
    ElTree,
    ElUpload,
    // ElInfiniteScroll,
    ElLoading,
    ElMessage,
    ElMessageBox,
    // ElNotification,
  } from 'element-plus';
  
  const components = [
    // ElAlert,
    // ElAside,
    // ElAutocomplete,
    ElAvatar,
    // ElBacktop,
    ElBadge,
    // ElBreadcrumb,
    // ElBreadcrumbItem,
    ElButton,
    ElButtonGroup,
    // ElCalendar,
    ElCard,
    // ElCarousel,
    // ElCarouselItem,
    // ElCascader,
    // ElCascaderPanel,
    ElCheckbox,
    ElCheckboxButton,
    ElCheckboxGroup,
    ElCol,
    ElCollapse,
    ElCollapseItem,
    ElCollapseTransition,
    ElColorPicker,
    ElContainer,
    ElDatePicker,
    ElDialog,
    ElDivider,
    // ElDrawer,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    // ElFooter,
    ElForm,
    ElFormItem,
    // ElHeader,
    ElIcon,
    ElImage,
    ElInput,
    ElInputNumber,
    // ElLink,
    // ElMain,
    ElMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElOption,
    ElOptionGroup,
    // ElPageHeader,
    ElPagination,
    // ElPopconfirm,
    // ElPopover,
    // ElPopper,
    ElProgress,
    ElRadio,
    // ElRadioButton,
    ElRadioGroup,
    // ElRate,
    ElRow,
    ElScrollbar,
    ElSelect,
    // ElSlider,
    // ElStep,
    // ElSteps,
    ElSubmenu,
    ElSwitch,
    ElTabPane,
    ElTable,
    ElTableColumn,
    ElTabs,
    ElTag,
    // ElTimePicker,
    // ElTimeSelect,
    // ElTimeline,
    // ElTimelineItem,
    ElTooltip,
    // ElTransfer,
    ElTree,
    ElUpload,
  ]
  
  const plugins = [
    // ElInfiniteScroll,
    ElLoading,
    ElMessage,
    ElMessageBox,
    // ElNotification,
  ]

export default (app: any) => {
    // 后期语言国际化
    // app.config.globalProperties.$ELEMENT = { locale };
    // locale.use(lang);
    components.forEach(component => {
        app.component(component.name, component);
    });

    plugins.forEach(plugin => {
        app.use(plugin);
    });

};
